name: Docker Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build image and push it
      uses: docker/build-push-action@v1
      with:
        username: oadm
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: oadm/godeploy
        tag_with_sha: true
  
  ansible-deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run playbook
        uses: jawher/action-ansible@2.9.7
        env:
          ANSIBLE_SSH_KEY: ${{ secrets.PRIVATE_KEY }}
        with:
          args: ansible-playbook -i ansible/inventory ansible/playbook.yml

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: ansible-deploy
  #   steps:

  #     - name: pull docker image
  #       uses: appleboy/ssh-action@master
  #       with:
  #         envs: GITHUB_SHA
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         key: ${{ secrets.PRIVATE_KEY }}
  #         script: sudo docker pull oadm/godeploy:sha-${GITHUB_SHA::7}

  #     - name: deploy docker image
  #       uses: appleboy/ssh-action@master
  #       with:
  #         envs: GITHUB_SHA
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         key: ${{ secrets.PRIVATE_KEY }}
  #         script: |
  #           sudo docker rm -f $(sudo docker ps -aq)
  #           sudo docker run -d -p 8080:8080 oadm/godeploy:sha-${GITHUB_SHA::7}
            