name: Build

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make build
          
    - name: Upload built result
      uses: actions/upload-artifact@v1
      with: 
        name: bin
        path: ./app